apiVersion: apps/v1
kind: Deployment
metadata:
  name: lookup
spec:
  selector:
    matchLabels:
      app: lookup
  replicas: 1
  template:
    metadata:
      labels:
        app: lookup
    spec:
      containers:
      - name: lookup
        image: icecreammatt/lookup:latest
        ports:
        - containerPort: 5000
