apiVersion: v1
kind: Service
metadata:
  name: lookup-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argo-lookup.stage.mattcarrier.net
spec:
  selector:
    app: lookup
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
