apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
spec:
  selector:
    matchLabels:
      app: excalidraw
  replicas: 1
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      containers:
      - name: excalidraw
        image: excalidraw:latest
        ports:
        - containerPort: 80
