apiVersion: v1
kind: Service
metadata:
  name: excalidraw-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argo-excalidraw.stage.mattcarrier.net
spec:
  selector:
    app: excalidraw
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8086
